---
title: "Blog"
output:
  html_document:
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: true
    toc_depth: 3
editor_options: 
  chunk_output_type: console
---
<style type="text/css">
h1.title {font-size: 1px;  color: White;}
body, td {font-size: 18px;}
code.r{font-size: 15px;}
pre {font-size: 12px}
</style>

```{r set up, include=FALSE}
# global options
knitr::opts_chunk$set(fig.width=5, 
                      fig.height=4, 
                      fig.align="center")
```


# Blog

Here is my blog. It contains more information about me.

---

## Data Science Handbook

I summarize theories, models, and questions in data science into an [online book](https://dennissxz.github.io/data-science-handbook). It will have three parts: Foundations, Algorithms, Machine Learning. I’m still writing it, and your feedback is highly appreciated.


---

## Stat2Life

I like to applying statistical thinking to life (Stat2Life) so that I can better understand the world and make the right decisions. To share my thinking, I have co-authored a book [*How to Do the Right Thing Consistently*](https://www.amazon.com/Logic-Doing-Things-Always-Chinese/dp/722011172X) with my like-minded university schoolmate Junlin Fu. There are always new ideas coming up, and I briefly summarize some keywords here. 


* Decision making: maximizing utility v.s. minimizing regret
  cf. maximizing likelihood v.s. minimizing loss.
  
* Markov Chain, absorbing state, and failure.

* Can one's utilty be a function of other's utility? The derivative can be positive, and can also be negative.

---

## Hobbies

- Hiking, squash, table tennis

- Cooking, baking

  Cooking is fun, baking is my therapy

- Chinese calligraphy

  I practiced Chinese calligraph for nine years from 6 to 15. I am proficient in writing regular script (楷书) and clerical script (隶书). During Chinese Spring Festivals, I write Spring couplets for friends and relatives.

- First-/third-person shooter games

  Strategies matter more than tactics.
  
- Trading index futures
  
  Trading is a dialogue with the world.

- Traveling
  
  I love exploring the world! I have been to 11 countries and regions, and I plan to make it 30 before my 30.

---

## Favorite Quotes

I belive one's favorite quotes can define his philosophy. Below are some of my favorite quotes.

> *One moment can change a day, one day can change a life, and one life can change the world.*

> *The best time to plant a tree is twenty years ago. The second-best time is now.* 
>
> <div style="text-align: right"> Dambisa Moyo, Dead Aid </div>

> *而世之奇伟瑰怪非常之观，常在于险远，而人之所罕至焉。故非有志者不能至也。有志矣，不随以止也，然力不足者，亦不能至也。有志与力，而又不随以怠，至于幽暗昏惑而无物以相之，亦不能至也。然力足以至焉，于人为可讥，而在己为有悔；尽吾志也而不能至者，可以无悔矣，其孰能讥之乎？*
>
> <div style="text-align: right"> 王安石（1021-1086）, 《游褒禅山记》</div>
>
> <span style="color:grey">Translation by Xie Baikui</span> 
>
> *So it is regrettable that numerous are excursionists visiting places which are near and easily accessible, but few are travelers who come to places far and dangerous, which, nevertheless, command the most sublime, grotesque and unique views, scarcely enjoyed by ordinary folks. One can never reach such places unless one has a strong will-power. But this alone, though unaffected by easy compliance with others’ inclination to remit one’s efforts, would not ensure the attainment of one’s goal, if not boosted by sufficient strength. A strong will-power and sufficient strength, though unaffected by that sort of easy compliance, would also fail to do so, if unassisted by extrinsic advantages, especially in dark and misleading circumstances. Given sufficient strength, failure to attain one’s objective entails scorn from others and regret from oneself. But, if one does not succeed in doing so after he has given full play to his will-power, he need not feel regret, and who would laugh him to scorn?* 
>
> <div style="text-align: right"> Wang Anshi (1021-1086), A Trip to Baochan Mountain </div>


> *There is only one heroism in the world: to see the world as it is, and to love it.* 
>
> <div style="text-align: right"> Romain Rolland, Life of Michelangelo </div>

> *I liked it, I was good at it, and I was really... I was alive.* 
>
> <div style="text-align: right"> Walter White, Breaking Bad Finale  </div>


